blank_issues_enabled: true
contact_links:
  - name: Add new ToDo
    about: made by config.yml
    # edit {username} and {repo} for your environment
    url: https://github.com/karaage0703/kanban/issues/new?template=custom.md&projects=karaage0703%2Fkanban%2F1&labels=kanban
